name: Python CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları indir (checkout)
      uses: actions/checkout@v2

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli kütüphaneleri yükle
      run: |
        pip install -r requirements.txt

    - name: Testleri çalıştır
      run: |
        pytest

    - name: Build işlemi (simülasyon)
      run: |
        echo "Build işlemi başarılı."

    - name: Deploy işlemi (simülasyon)
      run: |
        echo "Deploy işlemi başarıyla tamamlandı."
